image:
  name: hashicorp/terraform:0.14.3
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - cd terraform
  - rm -rf .terraform
  - terraform --version
  - terraform init

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -compact-warnings -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - ./terraform/planfile

apply:
  stage: apply
  script:
    - terraform apply -compact-warnings -input=false "planfile"
  # when: manual
  artifacts:
    paths:
      - ./host.txt
  dependencies:
    - plan

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
