image:
  name: hashicorp/terraform:0.14.3
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - terraform init
  - terraform force-unlock 242b4fa5-ecf8-0458-6c7d-788ff712bfe4

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - ./planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  # when: manual
  dependencies:
    - plan

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
