variables:
  TF_VAR_VM_DOMAIN_NAME: cloudmore
  TF_VAR_VM_NAME: TestVM
  TF_VAR_VM_ADMIN: azure-admin
  TF_VAR_LOCATION: WestEurope
  OW_CITY: Tallin
  OW_DEGREES_UNIT: C

image:
  name: hashicorp/terraform:0.14.3
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - cd terraform
  - rm -rf .terraform
  - terraform init

stages:
  - validate
  - plan
  - apply
  - deploy
  - destroy

# validate:
#   stage: validate
#   script:
#     - terraform validate

# plan:
#   stage: plan
#   script:
#     - terraform plan -compact-warnings -out "planfile"
#   dependencies:
#     - validate
#   artifacts:
#     paths:
#       - ./terraform/planfile

# apply:
#   stage: apply
#   script:
#     - terraform apply -compact-warnings -input=false "planfile"
#   # when: manual
#   dependencies:
#     - plan

deploy:
  stage: deploy
  before_script: []
  script:
    - pwd
    - cd docker
    - docker-compose up -d
  tags:
    - azure

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
