#cloud-config
package_update: true

packages:
    - docker.io
    - docker-compose
    - gitlab-runner

# create the docker group
groups:
    - docker

# assign a VM's default user, which is mydefaultuser, to the docker group
users:
    - default
    - name: mydefaultuser
      groups: docker

runcmd:
  - sudo gitlab-runner register \
      --non-interactive \
      --executor "shell"    \
      --url "https://gitlab.com/"   \
      --registration-token "xhMJpfQGpQ52FgUT1g8K"   \
      --description "shell-runner"  \
      --tag-list "azure,prod"   \
      --run-untagged="true" \
      --locked="false"
