#cloud-config

# create the docker group
groups:
    - docker
# assign a VM's default user, which is mydefaultuser, to the docker group
users:
    - default
    - name: mydefaultuser
      groups: docker
    - name: gitlab-runner
      groups: users, admin, sudo
      sudo: ALL=(ALL) NOPASSWD:ALL

apt:
  sources:
    docker.list:
      source: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable'
      keyid: 0EBFCD88 

package_update: true

packages:
   - docker-compose
   - docker-ce
   - ca-certificates

runcmd:
  - mkdir -p -m 0755 /work
  - curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
  - sudo apt-get install gitlab-runner -y
  - sudo gitlab-runner register --non-interactive --executor "shell"    --url "https://gitlab.com/"   --registration-token "xhMJpfQGpQ52FgUT1g8K"   --description "shell-runner"  --tag-list "azure,prod"   --run-untagged="false" --locked="false"
