#cloud-config
package_update: true

packages:
    - docker.io
    - docker-compose

# create the docker group
groups:
    - docker

# assign a VM's default user, which is mydefaultuser, to the docker group
users:
    - default
    - name: gitlab-runner
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: docker

runcmd:
  - mkdir -p -m 655 /work
  - curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
  - export GITLAB_RUNNER_DISABLE_SKEL=true; sudo -E apt-get install gitlab-runner
  - sudo gitlab-runner register --non-interactive --executor "shell"    --url "https://gitlab.com/"   --registration-token "xhMJpfQGpQ52FgUT1g8K"   --description "shell-runner"  --tag-list "azure,prod"   --run-untagged="false" --locked="false"
  - sudo usermod -aG docker gitlab-runner
  - sudo service docker restart
