#cloud-config
package_update: true


# create the docker group
groups:
    - docker

# assign a VM's default user, which is mydefaultuser, to the docker group
users:
    - default
    - name: gitlab-runner
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: docker

runcmd:
  - mkdir -p -m 0755 /work
  - curl -fsSL https://get.docker.com | sh
  - curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
  - apt-get install gitlab-runner docker-compose
  - gitlab-runner register --non-interactive --executor "shell"    --url "https://gitlab.com/"   --registration-token "xhMJpfQGpQ52FgUT1g8K"   --description "shell-runner"  --tag-list "azure,prod"   --run-untagged="false" --locked="false"
  - usermod -aG docker gitlab-runner
  - service docker restart
