#cloud-config

# create the docker group
groups:
    - docker
# assign a VM's default user, which is mydefaultuser, to the docker group
users:
    - default
    - name: gitlab-runner
      groups: docker
      sudo: ALL=(ALL) NOPASSWD:ALL
    - name: mydefaultuser
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: docker

apt:
  sources:
    docker.list:
      source: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable'
      keyid: 0EBFCD88 

package_update: true

packages:
   - gitlab-runner
   - docker-compose
   - docker-ce
   - ca-certificates

runcmd:
  - mkdir -p -m 0755 /work
  - gitlab-runner register --non-interactive --executor "shell"    --url "https://gitlab.com/"   --registration-token "xhMJpfQGpQ52FgUT1g8K"   --description "shell-runner"  --tag-list "azure,prod"   --run-untagged="false" --locked="false" --docker-privileged=true

power_state:
  delay: "now"
  mode: reboot
  message: First reboot
  condition: True
