version: '3.7'

services:

  openweather-exporter:
    image: billykwooten/openweather-exporter
    container_name: openweather-exporter
    restart: always
    ports:
      - 9091:9091
    environment:
      - OW_CITY=${OW_CITY}
      - OW_DEGREES_UNIT=${OW_DEGREES_UNIT}
      - OW_APIKEY=${OW_APIKEY}

  prometheus:
    image: prom/prometheus:v2.24.1
    depends_on:
      - openweather-exporter
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:6.6.1
    depends_on:
      - prometheus
    ports:
      - 80:3000
    user: "104"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always

volumes:
  prometheus:
  grafana:
