version: '3.1'

services:

  openweather-exporter:
    image: billykwooten/openweather-exporter
    container_name: openweather-exporter
    restart: always
    ports:
      - 9091:9091
    environment:
      - OW_CITY=Tallin
      - OW_DEGREES_UNIT=C
      - OW_APIKEY=cb33357e4410403486d872416862b6fb

  prometheus:
    image: prom/prometheus:v2.24.1
    depends_on:
      - openweather-exporter
    volumes:
      - /tmp/prometheus:/prometheus:z
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:6.6.1
    depends_on:
      - prometheus
    ports:
      - 80:3000
    user: "104"
    volumes:
      - /tmp/grafana:/var/lib/grafana:z
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always
