version: '3.7'

services:

  openweather-exporter:
    image: billykwooten/openweather-exporter
    networks:
      - traefik
    container_name: openweather-exporter
    restart: always
    expose: 
      - 9091
    environment:
      - OW_CITY=${OW_CITY}
      - OW_DEGREES_UNIT=${OW_DEGREES_UNIT}
      - OW_APIKEY=${OW_APIKEY}
    labels:
      - traefik.http.routers.metrics.rule=PathPrefix(`/metrics`)
      - traefik.http.routers.metrics.entrypoints=http,https
      - traefik.docker.network=traefik

  prometheus:
    image: prom/prometheus:v2.24.1
    networks:
      - traefik
    depends_on:
      - openweather-exporter
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always
    labels:
      - traefik.enable=false

  grafana:
    image: grafana/grafana:6.6.1
    networks:
      - traefik
    depends_on:
      - prometheus
    user: "104"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    labels:
      - traefik.http.routers.grafana.rule=PathPrefix(`/`)
      - traefik.http.routers.grafana.entrypoints=http,https
      - traefik.docker.network=traefik

  traefik:
    container_name: traefik
    command: --web -c /etc/traefik/traefik.yaml
    image: traefik:2.4.2
    restart: always
    labels:
      - traefik.http.routers.traefik.rule=Host(`${TF_VAR_VM_DOMAIN_NAME}.${TF_VAR_LOCATION}.cloudapp.azure.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.traefik.entrypoints=traefik
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=auth,dashboard
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$10$$jiNkcnNkYiW6OJETlYJ4W.JufWIBAj4cceuUaXfIkitItvUkMDWJe"
      - traefik.docker.network=traefik
      - traefik.http.middlewares.dashboard.redirectregex.regex=.*
      - traefik.http.middlewares.dashboard.redirectregex.replacement=https://${TF_VAR_VM_DOMAIN_NAME}.${TF_VAR_LOCATION}.cloudapp.azure.com:9000/dashboard/
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/:/etc/traefik/
      - /acme

networks:
  traefik:
    driver: overlay
    attachable: true
    external:
      name: traefik

